// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TAKSuite.Data;

#nullable disable

namespace TAKSuite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508160000_AddTimeWindowsJson")]
    partial class AddTimeWindowsJson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
