// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAKSuite.Data;

#nullable disable

namespace TAKSuite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522100000_AddUserTheme")]
    partial class AddUserTheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
