// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TAKSuite.Data;

#nullable disable

namespace TAKSuite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505110000_AddPoiNameToTask")]
    partial class AddPoiNameToTask
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
