// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TAKSuite.Data;

#nullable disable

namespace TAKSuite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522110000_AddDocumentDescription")]
    partial class AddDocumentDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
